controller_list:
 - name: rh_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - rh_FFJ4
     - rh_FFJ3
     - rh_FFJ2
     - rh_FFJ1
     - rh_RFJ4
     - rh_RFJ3
     - rh_RFJ2
     - rh_RFJ1
     - rh_THJ5
     - rh_THJ4
     - rh_THJ3
     - rh_THJ2
     - rh_THJ1
