first_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  maxIterations: 100
  epsilon: 0.001
  lambda: 0.01
  root_name: palm
  tip_name: fftip
ring_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  maxIterations: 100
  lambda: 0.01
  epsilon: 0.001
  tip_name: rftip
thumb:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  maxIterations: 100
  lambda: 0.01
  epsilon: 0.001
  tip_name: thtip
